source 'https://cdn.cocoapods.org/'

install! 'cocoapods',
  :disable_input_output_paths => true,
  :generate_multiple_pod_projects => true

#use_frameworks!
use_frameworks! :linkage => :static

## ignore all warnings from all dependencies
#inhibit_all_warnings!

#workspace '${POD_NAME}.xcworkspace'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => './'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths
    ${INCLUDED_PODS}
  end
end

